name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  main:
    name: CI
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: wget "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
      - name: Decompress
        run: unzip "./dist.zip"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_dir: ./dist/
          force_orphan: true
